# Generated by Django 5.2.7 on 2025-10-15 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name_plural': 'Profiles'},
        ),
        migrations.AlterField(
            model_name='attachment',
            name='filename',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
